version: "1.0.0"
services:
  app:
    build: .
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=imageDB
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10